# Generated by Django 5.1.6 on 2025-02-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='card',
            name='card_issuer',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('rupay', 'RuPay')], default='2025-02-02', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
