# Generated by Django 5.1.6 on 2025-02-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0004_alter_card_card_issuer_alter_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
