# Generated by Django 5.1.6 on 2025-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], db_default='debit', max_length=50),
        ),
    ]
