# Generated by Django 5.1.6 on 2025-02-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0006_alter_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
