# Generated by Django 5.1.6 on 2025-02-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0007_card_card_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subtype',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('debit', 'Debit')], max_length=15, null=True),
        ),
    ]
