# Generated by Django 5.1.6 on 2025-02-15 23:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0008_transaction_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
