# Generated by Django 5.1.6 on 2025-02-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0009_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subtype',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expenditure', 'Expenditure'), ('transfer', 'Transfer')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('debit', 'Debit')], max_length=15),
        ),
    ]
