# Generated by Django 5.1.6 on 2025-02-16 02:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0011_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('analysis', django.db.models.manager.Manager()),
            ],
        ),
    ]
