# Generated by Django 5.1.6 on 2025-02-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0012_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
    ]
