# Generated by Django 5.1.6 on 2025-02-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0013_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_data',
            field=models.ImageField(upload_to='qr_codes/'),
        ),
    ]
