# Generated by Django 5.1.6 on 2025-02-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0014_alter_qrcode_qr_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='qr_data',
            new_name='qr_image',
        ),
    ]
