# Generated by Django 5.1.6 on 2025-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0015_rename_qr_data_qrcode_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+2348129341700', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
