# Generated by Django 5.1.6 on 2025-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eWallet', '0016_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_after',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_before',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
